// Best-effort detection of the authoring tool that produced a SCORM package,
// from the manifest (its generator comment) and the package's file signatures.

interface Sig {
  name: string;
  re: RegExp;
}

// Order matters — more specific signatures first.
const SIGNATURES: Sig[] = [
  { name: 'Lectora', re: /lectora|trivantis/ },
  { name: 'Articulate Storyline', re: /storyline|story_content\/|(^|\/)story\.html/m },
  { name: 'Articulate Rise', re: /articulate rise|(^|\/)scormcontent\//m },
  { name: 'Articulate', re: /articulate/ },
  { name: 'Adobe Captivate', re: /captivate|\/cpm\.js|assets\/js\/cphost/ },
  { name: 'iSpring', re: /ispring/ },
  { name: 'Adapt', re: /adapt[\s_-]?learning|adaptframework/ },
  { name: 'dominKnow', re: /dominknow/ },
  { name: 'Elucidat', re: /elucidat/ },
  { name: 'Gomo', re: /gomolearning|\bgomo\b/ },
  { name: 'Easygenerator', re: /easygenerator/ },
  { name: 'Rise 360', re: /rise360/ },
  { name: 'Camtasia', re: /camtasia|techsmith/ },
  { name: 'Dreamweaver', re: /dreamweaver/ },
  { name: 'iSpring Suite', re: /ispring suite/ },
];

export function detectAuthoringTool(manifestXml: string, paths: string[]): string | undefined {
  const hay = `${manifestXml}\n${paths.join('\n')}`.toLowerCase();
  for (const sig of SIGNATURES) {
    if (sig.re.test(hay)) return sig.name;
  }

  // Fall back to the manifest generator comment, cleaned up.
  const gen = manifestXml.match(/(?:generated by|created with)\s*:?\s*"?([^"\n*<]+)/i)?.[1];
  if (gen) {
    const name = gen
      .replace(/\bpublisher\b/i, '')
      .replace(/\bversion\b.*$/i, '')
      .replace(/v?\.?\s*\d[\d.()]*.*$/, '')
      .replace(/\bfor\b\s+.*$/i, '')
      .replace(/["',]/g, '')
      .trim();
    if (name.length > 1 && name.length <= 32) return name;
  }
  return undefined;
}
